# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('long_name', models.CharField(max_length=255)),
                ('period', models.IntegerField()),
                ('min_per_period', models.IntegerField()),
            ],
        ),
    ]
