# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archived_team_names',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FibaGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiba_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fiba_id', models.IntegerField(blank=True, null=True)),
                ('data_json', models.TextField(blank=True, null=True)),
                ('home_team_number', models.IntegerField(blank=True, null=True)),
                ('away_team_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiba_game_infos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FibaGamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField(blank=True, null=True)),
                ('player_number', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fiba_game_players',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('game_type', models.IntegerField(blank=True, null=True)),
                ('home_pts', models.IntegerField(blank=True, null=True)),
                ('away_pts', models.IntegerField(blank=True, null=True)),
                ('periods', models.IntegerField(blank=True, null=True)),
                ('pre_game_article_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_game_article_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(blank=True, null=True)),
                ('secs_remaining', models.IntegerField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, max_length=255, null=True)),
                ('action_subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('scoring', models.NullBooleanField()),
                ('success', models.NullBooleanField()),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('lineup', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Game')),
            ],
            options={
                'db_table': 'game_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GamePeriodScoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(blank=True, null=True)),
                ('home_pts', models.IntegerField(blank=True, null=True)),
                ('away_pts', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Game')),
            ],
            options={
                'db_table': 'game_period_scorings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GamePlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_jersey_number', models.IntegerField(blank=True, null=True)),
                ('seconds_played', models.IntegerField(blank=True, null=True)),
                ('fg_made', models.IntegerField(blank=True, null=True)),
                ('fg_attempts', models.IntegerField(blank=True, null=True)),
                ('three_pt_made', models.IntegerField(blank=True, null=True)),
                ('three_pt_attempts', models.IntegerField(blank=True, null=True)),
                ('ft_made', models.IntegerField(blank=True, null=True)),
                ('ft_attempts', models.IntegerField(blank=True, null=True)),
                ('offensive_reb', models.IntegerField(blank=True, null=True)),
                ('defensive_reb', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('steals', models.IntegerField(blank=True, null=True)),
                ('blocks', models.IntegerField(blank=True, null=True)),
                ('turnovers', models.IntegerField(blank=True, null=True)),
                ('personal_fouls', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('started', models.NullBooleanField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Game')),
                ('my_team_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_game_player_stat', to='humblebola.GamePlayerStat')),
                ('opp_team_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opp_game_player_stat', to='humblebola.GamePlayerStat')),
            ],
            options={
                'db_table': 'game_player_stats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameTeamStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_played', models.IntegerField(blank=True, null=True)),
                ('fg_made', models.IntegerField(blank=True, null=True)),
                ('fg_attempts', models.IntegerField(blank=True, null=True)),
                ('three_pt_made', models.IntegerField(blank=True, null=True)),
                ('three_pt_attempts', models.IntegerField(blank=True, null=True)),
                ('ft_made', models.IntegerField(blank=True, null=True)),
                ('ft_attempts', models.IntegerField(blank=True, null=True)),
                ('offensive_reb', models.IntegerField(blank=True, null=True)),
                ('defensive_reb', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('steals', models.IntegerField(blank=True, null=True)),
                ('blocks', models.IntegerField(blank=True, null=True)),
                ('turnovers', models.IntegerField(blank=True, null=True)),
                ('personal_fouls', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('fastbreak_pts', models.IntegerField(blank=True, null=True)),
                ('fastbreak_attempts', models.IntegerField(blank=True, null=True)),
                ('second_chance_pts', models.IntegerField(blank=True, null=True)),
                ('turnover_pts', models.IntegerField(blank=True, null=True)),
                ('team_offensive_reb', models.IntegerField(blank=True, null=True)),
                ('team_defensive_reb', models.IntegerField(blank=True, null=True)),
                ('team_turnovers', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Game')),
            ],
            options={
                'db_table': 'game_team_stats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('periods', models.IntegerField(blank=True, null=True)),
                ('mins_per_period', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leagues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_jersey_number', models.IntegerField(blank=True, null=True)),
                ('player_type', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('drafted', models.CharField(blank=True, max_length=255, null=True)),
                ('highschool', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('real_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('real_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.League')),
            ],
            options={
                'db_table': 'players',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlayerLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.League')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Player')),
            ],
            options={
                'db_table': 'player_leagues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlayerTournamentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Player')),
            ],
            options={
                'db_table': 'player_tournament_teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SchemaMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'schema_migrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.League')),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sub_tournaments_count', models.IntegerField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.League')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Tournament')),
            ],
            options={
                'db_table': 'tournaments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('reset_password_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reset_password_sent_at', models.DateTimeField(blank=True, null=True)),
                ('remember_created_at', models.DateTimeField(blank=True, null=True)),
                ('sign_in_count', models.IntegerField()),
                ('current_sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('current_sign_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_sign_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.League')),
            ],
            options={
                'db_table': 'videos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='playertournamentteam',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='playertournamentteam',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='gameteamstat',
            name='opp_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opp_game_team_stat', to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='gameteamstat',
            name='opp_team_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.GameTeamStat'),
        ),
        migrations.AddField(
            model_name='gameteamstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_game_team_stat', to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='gameplayerstat',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Player'),
        ),
        migrations.AddField(
            model_name='gameplayerstat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='opp_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opp_game_event', to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Player'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_game_event', to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_game', to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_game', to='humblebola.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.League'),
        ),
        migrations.AddField(
            model_name='fibagameplayer',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Game'),
        ),
        migrations.AddField(
            model_name='fibagameplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Player'),
        ),
        migrations.AddField(
            model_name='fibagameinfo',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Game'),
        ),
        migrations.AddField(
            model_name='archivedteamname',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='playertournamentteam',
            unique_together=set([('player', 'team', 'tournament')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerleague',
            unique_together=set([('player', 'league')]),
        ),
    ]
