# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humblebola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='short_name',
            new_name='title',
        ),
    ]
