# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-19 14:54
from __future__ import unicode_literals
from datetime import datetime, time
from django.db import migrations, models
import django.db.models.deletion



def map_tournament_games(apps, schema_editor):
    Game = apps.get_model("humblebola", "Game")
    Tournament = apps.get_model("humblebola", "Tournament")
    for game in Game.objects.all():
        if game.league.id == 1:
            tournament = Tournament.objects.get(
                league_id=game.league.id,
                start_date__lte=datetime.combine(game.schedule, time.min),
                end_date__gte=datetime.combine(game.schedule, time.min),
                parent_id__isnull=False)
            game.tournament_id = tournament.id
            game.save()
        else:
            tournament = Tournament.objects.get(
                league_id=game.league.id,
                start_date__lte=datetime.combine(game.schedule, time.min),
                end_date__gte=datetime.combine(game.schedule, time.min))
            game.tournament_id = tournament.id
            game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('humblebola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humblebola.Tournament'),
        ),
        migrations.RunPython(map_tournament_games)
    ]
