# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humblebola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedteamnames',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='fibagameinfos',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Games'),
        ),
        migrations.AlterField(
            model_name='fibagameplayers',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Games'),
        ),
        migrations.AlterField(
            model_name='fibagameplayers',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Players'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Games'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='opp_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_game_event', to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Players'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_event', to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='gameperiodscorings',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Games'),
        ),
        migrations.AlterField(
            model_name='gameplayerstats',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Games'),
        ),
        migrations.AlterField(
            model_name='gameplayerstats',
            name='my_team_stat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_player_stat', to='humblebola.GamePlayerStats'),
        ),
        migrations.AlterField(
            model_name='gameplayerstats',
            name='opp_team_stat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_game_player_stat', to='humblebola.GamePlayerStats'),
        ),
        migrations.AlterField(
            model_name='gameplayerstats',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Players'),
        ),
        migrations.AlterField(
            model_name='gameplayerstats',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='games',
            name='away_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='games',
            name='home_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='games',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Leagues'),
        ),
        migrations.AlterField(
            model_name='gameteamstats',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Games'),
        ),
        migrations.AlterField(
            model_name='gameteamstats',
            name='opp_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_game_team_stat', to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='gameteamstats',
            name='opp_team_stat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.GameTeamStats'),
        ),
        migrations.AlterField(
            model_name='gameteamstats',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_team_stat', to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='playerleagues',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Leagues'),
        ),
        migrations.AlterField(
            model_name='playerleagues',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Players'),
        ),
        migrations.AlterField(
            model_name='players',
            name='current_league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Leagues'),
        ),
        migrations.AlterField(
            model_name='players',
            name='current_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='playertournamentteams',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Players'),
        ),
        migrations.AlterField(
            model_name='playertournamentteams',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Teams'),
        ),
        migrations.AlterField(
            model_name='playertournamentteams',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Tournaments'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Leagues'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Leagues'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Tournaments'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humblebola.Leagues'),
        ),
    ]
