# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humblebola', '0002_archivedteamname_authgrouppermission_authusergroup_authuseruserpermission_fibagameinfo_fibagameplaye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'managed': False, 'ordering': ('league', 'id')},
        ),
    ]
