# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humblebola', '0003_auto_20160315_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='archivedteamname',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authusergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fibagameinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fibagameplayer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gameevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gameperiodscoring',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gameplayerstat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gameteamstat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playerleague',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playertournamentteam',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schemamigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'managed': True, 'ordering': ('league', 'id')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='league_id',
        ),
    ]
